#!/usr/bin/env python3
"""
confirm_release.py — create a DSR release folder skeleton when a release is confirmed.

Canonical storage: Google Shared Drive "DSR Releases", mounted locally.
Convention:
    <drive>/My Drive/<year>/<Artist(s)> - <Title>/
        <audio files at top>
        <contract files at top>
        metadata.yaml
        lyrics/                 (lyric-flagger output)

The path is configurable via env DSR_RELEASES_ROOT (default: "L:/My Drive").
That root must contain a year folder for each release year.

Examples:
    python confirm_release.py --artist DirtySnatcha --title "Rise EP" --date 2026-05-29
    python confirm_release.py --artist "Dark Matter" --title "Barooka" --date 2026-05-06 \\
        --tracks "Run The Game" --soundcloud "https://soundcloud.com/.../run-the-game"
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path

DEFAULT_DRIVE_ROOT = Path(os.environ.get("DSR_RELEASES_ROOT", r"L:/My Drive/DSR Releases"))
SUBDIRS = ["lyrics"]  # only tooling output gets a subfolder; everything else flat (matches Kaime convention)


def fmt_release_folder(artist: str, title: str) -> str:
    """Return '<Artist> - <Title>' with whitespace tidied. No date prefix (matches existing DSR convention)."""
    artist = " ".join(artist.split()).strip()
    title = " ".join(title.split()).strip()
    return f"{artist} - {title}"


def parse_list(value: str | None, *, keep_empty: bool = False) -> list[str]:
    """Split on comma. With keep_empty=True, preserve empty positions (for URL lists that align positionally with --tracks)."""
    if not value:
        return []
    parts = [v.strip() for v in value.split(",")]
    if keep_empty:
        return parts
    return [p for p in parts if p]


def metadata_yaml(args: argparse.Namespace, release_folder: str) -> str:
    """Render metadata.yaml. Hand-written so we don't pull pyyaml just for this."""
    tracks = parse_list(args.tracks)
    soundcloud = parse_list(args.soundcloud, keep_empty=True)
    spotify = parse_list(args.spotify, keep_empty=True)
    durations = parse_list(args.durations, keep_empty=True)
    label = args.label or "DirtySnatcha Records"
    distributor = args.distributor or "Ingrooves"

    lines: list[str] = []
    lines.append(f"# {release_folder}")
    lines.append(f"# Generated by confirm_release.py on {date.today().isoformat()}.")
    lines.append("# Edit by hand to fill in ISRCs, splits, etc.")
    lines.append("")
    lines.append(f"title: {args.title}")
    lines.append(f"artist: {args.artist}")
    lines.append(f"artists: [{args.artist}]   # primary + features; expand as needed")
    lines.append(f"release_date: {args.date}")
    lines.append(f"label: {label}")
    lines.append(f"distributor: {distributor}")
    lines.append('catalog_number: ""')
    lines.append('upc: ""')
    lines.append("")
    lines.append("tracks:")
    if tracks:
        for i, t in enumerate(tracks):
            sc = soundcloud[i] if i < len(soundcloud) else ""
            sp = spotify[i] if i < len(spotify) else ""
            dur = durations[i] if i < len(durations) else ""
            lines.append(f"  - title: {t}")
            lines.append('    isrc: ""')
            lines.append(f'    duration: "{dur}"' if dur else '    duration: ""    # m:ss; filled by lyric-flagger')
            if sc:
                lines.append(f"    soundcloud: {sc}")
            if sp:
                lines.append(f"    spotify: {sp}")
            lines.append("    explicit: unknown   # filled by lyric-flagger")
            lines.append('    language: ""        # filled by lyric-flagger')
    else:
        lines.append("  []")
    lines.append("")
    lines.append("splits:")
    lines.append("  # Per-track split sheets live in this list. Format:")
    lines.append("  # - track: <title>")
    lines.append("  #   shares:")
    lines.append("  #     <legal name>: <percent>")
    lines.append("  []")
    lines.append("")
    lines.append("artwork:")
    lines.append('  cover: ""        # path or filename of 3000x3000 cover')
    lines.append('  square: ""')
    lines.append('  banner: ""')
    lines.append("")
    lines.append("contracts:")
    lines.append("  # files at top of release folder, listed here for traceability")
    lines.append("  []")
    lines.append("")
    lines.append('notes: ""')
    lines.append("")
    return "\n".join(lines)


def slugify(text: str) -> str:
    import re
    s = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    s = re.sub(r"-+", "-", s)
    return s


REPO_ROOT = Path(__file__).resolve().parents[2]
LYRIC_FLAGGER_DIR = REPO_ROOT / "scripts" / "lyric-flagger"
LYRIC_FLAGGER_PY = LYRIC_FLAGGER_DIR / "lyric_flagger.py"
LYRIC_FLAGGER_VENV_PY = LYRIC_FLAGGER_DIR / ".venv" / "Scripts" / "python.exe"
AUDIO_EXTS = {".wav", ".flac", ".mp3", ".m4a", ".aiff", ".aif"}


def run_lyric_flagger(release_dir: Path, args) -> None:
    """If audio files exist at the top of the release dir, run lyric_flagger on them
    and write outputs to <release>/lyrics/. Skip silently if no audio yet."""
    import subprocess

    audio = sorted(p for p in release_dir.iterdir() if p.is_file() and p.suffix.lower() in AUDIO_EXTS)
    if not audio:
        print(f"lyrics:   no audio files in {release_dir} yet — skipping lyric-flagger.")
        print(f"          Drop WAVs at the top of the release folder, then re-run this script (or run lyric_flagger.py directly).")
        return

    if not LYRIC_FLAGGER_PY.exists():
        print(f"WARN: lyric_flagger.py not found at {LYRIC_FLAGGER_PY}; skipping lyric pass.")
        return

    # Guard: don't overwrite human-verified lyrics. If any existing .txt in lyrics/ says human-verified, skip.
    lyrics_dir = release_dir / "lyrics"
    existing_txts = list(lyrics_dir.glob("*.txt")) if lyrics_dir.exists() else []
    if existing_txts:
        verified = any("human-verified" in p.read_text(encoding="utf-8", errors="ignore") for p in existing_txts)
        if verified:
            print(f"lyrics:   {lyrics_dir} already contains human-verified files — skipping (delete or move them to force re-run).")
            return

    python_bin = LYRIC_FLAGGER_VENV_PY if LYRIC_FLAGGER_VENV_PY.exists() else Path(sys.executable)

    # Resolve vocab: explicit --vocab wins; else look for vocab/<artist-slug>-<release-slug>.txt
    vocab_path = args.vocab
    if vocab_path is None:
        candidate = LYRIC_FLAGGER_DIR / "vocab" / f"{slugify(args.artist)}-{slugify(args.title)}.txt"
        if candidate.exists():
            vocab_path = candidate
            print(f"lyrics:   using vocab {candidate}")
        else:
            print(f"lyrics:   no vocab file at {candidate} — running without prime (less accurate on processed vocals).")

    cmd = [
        str(python_bin), str(LYRIC_FLAGGER_PY),
        "--no-vad",
        "--whisper-model", args.whisper_model,
        "--release-dir", str(release_dir),
    ]
    if vocab_path:
        cmd += ["--vocab", str(vocab_path)]
    cmd += [str(p) for p in audio]

    print(f"lyrics:   running lyric_flagger on {len(audio)} audio file(s) — this can take a few minutes per track.")
    rc = subprocess.call(cmd)
    if rc == 0:
        print(f"lyrics:   complete. Output in {release_dir / 'lyrics'}")
    else:
        print(f"lyrics:   lyric_flagger exited with code {rc} — check console output above.")


def ensure_dir(p: Path) -> tuple[Path, bool]:
    """Create p if missing. Return (path, created)."""
    if p.exists():
        return p, False
    p.mkdir(parents=True, exist_ok=False)
    return p, True


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--artist", required=True, help="Primary artist (or 'A x B' for collab — match existing DSR folder convention).")
    p.add_argument("--title", required=True, help="Release title (e.g. 'Rise EP').")
    p.add_argument("--date", required=True, help="Release date YYYY-MM-DD. Year is used for the year-folder.")
    p.add_argument("--year", help="Override year folder (default: derived from --date).")
    p.add_argument("--label", default="DirtySnatcha Records", help="Label name for metadata.yaml.")
    p.add_argument("--distributor", default="Ingrooves", help="Distributor for metadata.yaml.")
    p.add_argument("--tracks", help="Comma-separated track titles.")
    p.add_argument("--soundcloud", help="Comma-separated SoundCloud URLs (positional with --tracks).")
    p.add_argument("--spotify", help="Comma-separated Spotify URLs (positional with --tracks).")
    p.add_argument("--durations", help='Comma-separated track durations as "m:ss" (positional with --tracks). Example: "3:15, 3:15, 3:18, 3:05".')
    p.add_argument("--drive-root", type=Path, default=DEFAULT_DRIVE_ROOT,
                   help=f"Drive mount path holding year folders. Default: {DEFAULT_DRIVE_ROOT} (env DSR_RELEASES_ROOT).")
    p.add_argument("--no-metadata", action="store_true", help="Don't write metadata.yaml.")
    p.add_argument("--no-lyrics", action="store_true",
                   help="Skip the lyric-flagger run. By default, after creating the skeleton, any audio at the top of the release dir gets transcribed + flagged into lyrics/.")
    p.add_argument("--whisper-model", default="medium", help="Whisper model for lyric-flagger (default: medium).")
    p.add_argument("--vocab", type=Path,
                   help="Vocab file path for lyric-flagger. Default: scripts/lyric-flagger/vocab/<artist-slug>-<release-slug>.txt if it exists.")
    p.add_argument("--print-paths", action="store_true", help="After creating, print JSON with the resolved paths (release_dir, lyrics_dir, year_dir).")
    args = p.parse_args()

    try:
        year = args.year or args.date.split("-")[0]
        if not (year.isdigit() and len(year) == 4):
            raise ValueError(f"Year must be 4 digits, got: {year!r}")
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    drive_root: Path = args.drive_root
    if not drive_root.exists():
        print(f"ERROR: Drive mount not found: {drive_root}", file=sys.stderr)
        print("       Ensure Google Drive desktop is running and the shared drive is mounted.", file=sys.stderr)
        print("       Override with --drive-root or env DSR_RELEASES_ROOT.", file=sys.stderr)
        return 2

    year_dir = drive_root / year
    year_dir, year_created = ensure_dir(year_dir)
    if year_created:
        print(f"created  year folder: {year_dir}")

    release_folder = fmt_release_folder(args.artist, args.title)
    release_dir = year_dir / release_folder
    release_dir, release_created = ensure_dir(release_dir)
    print(f"{'created' if release_created else 'exists '}  release folder: {release_dir}")

    for sub in SUBDIRS:
        sd, made = ensure_dir(release_dir / sub)
        print(f"{'created' if made else 'exists '}  {sub}/: {sd}")

    if not args.no_metadata:
        meta_path = release_dir / "metadata.yaml"
        if meta_path.exists():
            print(f"exists   metadata.yaml: {meta_path} (left untouched)")
        else:
            meta_path.write_text(metadata_yaml(args, release_folder), encoding="utf-8")
            print(f"created  metadata.yaml: {meta_path}")

    if not args.no_lyrics:
        run_lyric_flagger(release_dir, args)

    if args.print_paths:
        print(json.dumps({
            "year_dir": str(year_dir),
            "release_dir": str(release_dir),
            "lyrics_dir": str(release_dir / "lyrics"),
        }, indent=2))

    return 0


if __name__ == "__main__":
    sys.exit(main())
