import Link from "next/link";
import { serverClient } from "@/lib/supabase";

export const dynamic = "force-dynamic";

type Report = {
  id: string;
  period: string;
  window_start: string;
  window_end: string;
  payload: any;
  markdown: string | null;
  created_at: string;
};

async function load(): Promise<Report[]> {
  try {
    const sb = serverClient();
    const { data, error } = await sb
      .from("reports")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(30);
    if (error) throw error;
    return (data ?? []) as Report[];
  } catch {
    return [];
  }
}

function fmt(dt: string): string {
  try {
    return new Date(dt).toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return dt;
  }
}

export default async function Reports() {
  const reports = await load();

  return (
    <div className="space-y-6">
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-2xl">reports</h1>
          <p className="text-sm text-muted mt-1">
            daily + weekly rollups generated by the reporting agent. run{" "}
            <code className="text-accent">
              python agents/reporting.py --period daily
            </code>{" "}
            to produce a new one.
          </p>
        </div>
      </div>

      {reports.length === 0 && (
        <div className="text-muted text-sm">
          no reports yet. once you run the reporting agent (or the supervisor
          triggers it on schedule), they'll appear here.
        </div>
      )}

      <div className="space-y-4">
        {reports.map((r) => {
          const s = r.payload ?? {};
          return (
            <div
              key={r.id}
              className="px-4 py-3 bg-white/[0.02] border border-white/10 rounded"
            >
              <div className="flex items-baseline justify-between mb-2">
                <div>
                  <span className="text-accent uppercase text-xs tracking-wide">
                    {r.period}
                  </span>
                  <span className="ml-2 text-sm">
                    {r.window_start.slice(0, 10)} → {r.window_end.slice(0, 10)}
                  </span>
                </div>
                <div className="text-xs text-muted">{fmt(r.created_at)}</div>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs mb-3">
                <Stat label="out sent" value={s.outbound_sent ?? 0} />
                <Stat label="inbound" value={s.inbound_received ?? 0} />
                <Stat label="offers" value={s.offers_received ?? 0} />
                <Stat
                  label="reply rate"
                  value={
                    s.reply_rate != null
                      ? `${Math.round(s.reply_rate * 100)}%`
                      : "—"
                  }
                />
                <Stat label="held" value={s.held_for_review ?? 0} />
                <Stat label="rejected" value={s.rejected ?? 0} />
                <Stat label="bounces" value={s.bounces ?? 0} />
                <Stat label="dnc added" value={s.dnc_added ?? 0} />
              </div>

              {r.markdown && (
                <details>
                  <summary className="text-xs text-muted cursor-pointer hover:text-ink">
                    show narrative
                  </summary>
                  <pre className="mt-2 text-xs text-muted whitespace-pre-wrap">
                    {r.markdown}
                  </pre>
                </details>
              )}
            </div>
          );
        })}
      </div>

      <div className="text-xs text-muted pt-4 border-t border-white/10">
        <Link href="/dashboard" className="hover:text-ink">
          ← dashboard
        </Link>
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="px-2 py-1 bg-white/[0.02] rounded">
      <div className="text-[10px] text-muted uppercase tracking-wide">
        {label}
      </div>
      <div className="text-sm mt-0.5">{value}</div>
    </div>
  );
}
